image: juampynr/drupal8ci:latest

variables:
  MYSQL_ALLOW_EMPTY_PASSWORD: 1

stages:
  - build
  - test
  - deploy

build:test:
  stage: build
  script:
    - composer install
  services:
    - mariadb:10.3

build:prod:
  stage: build
  script:
    - composer install --no-dev
  artifacts:
    paths:
      - vendor
      - web/core
      - web/modules
      - web/themes
      - web/profiles
      - web/libraries

deploy:prod:
  stage: deploy
  script:
    - git add ./vendor ./web --force
    - git commit --author="GitLab CI <james+gitlab@lullabot.com>" -m "Compiling for $CI_COMMIT_SHA."
    - scripts/ci-github-push.sh $CI_COMMIT_REF_NAME
  dependencies:
    - build:prod
#  only:
#    - tags

code_sniffer:
  stage: test
  script:
    - robo install:dependencies
    - vendor/bin/phpcs --config-set installed_paths vendor/drupal/coder/coder_sniffer
    - mkdir -p artifacts/phpcs
    - vendor/bin/phpcs --standard=Drupal --report=junit --report-junit=artifacts/phpcs/phpcs.xml web/modules/custom
    - vendor/bin/phpcs --standard=DrupalPractice --report=junit --report-junit=artifacts/phpcs/phpcs.xml web/modules/custom
  artifacts:
    paths:
      - artifacts/phpcs/phpcs.xml
  dependencies:
    - build:test
